### ISSUE TITLE
Make diagnostic messages optional?

### ISSUE THREAD

**Issue by dmfv** [cvs0/ptrX#2]
It's good to make logging optional.
If anyone will want to try this library for more than demonstration cases they certainly will want to remove logging to increase the speed.

I suggest to make logging optional by adding template parameter or your own wrapper class for logging to separate memory manager class and logging logic.

**Comment by dmfv** [comment]
Also maybe a good thing to change all int pointer to template parameter

**Comment by cvs0** [comment]
I'll have these out by 10PM UTC-7.
